<?php


use JetBrains\PhpStorm\Pure;

class Cylinder1 extends Circle1
{
    public int|float $height;

    #[Pure] public function __construct(string $name, int $radius, int $height)
    {
        parent::__construct($name, $radius);
        $this->height = $height;
    }
    public function __toString(): string
    {
        // TODO: Implement __toString() method.
        return $this->height;
    }

    public function setName(string $name): void
    {
        parent::setName($name); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }
    /**
     * @param float|int $height
     */
    public function setHeight(float|int $height): void
    {
        $this->height = $height;
    }

    /**
     * @return float|int
     */
    public function getHeight(): float|int
    {
        return $this->height;
    }

    #[Pure] public function calculateCylinderArea(): int
    {
        return parent::calculateCircleArea() * 2 + 2 * parent::calculateCircePerimeter() * $this->height;
    }

    #[Pure] public function calculateCylinderVolume(): int
    {
        return parent::calculateCircleArea() * $this->height;
    }
}